---
cluster:
  hosts:
    tredf-antonioelsonmoreira.tangrama.com.br:
      ansible_user: root
      ansible_host: tredf-antonioelsonmoreira.tangrama.com.br
      host: tredf-antonioelsonmoreira
      hostname: tredf-antonioelsonmoreira.tangrama.com.br
      swarm_node:
        labels:
          type: manager
          env: production

  children:
    cluster_managers:
      children:
        cluster_manager:
          hosts:
            tredf-antonioelsonmoreira.tangrama.com.br:

        cluster_managers_additional:
          hosts:

    cluster_workers:
      hosts:
